#!/bin/sh
echo "******** Running serf swarm update ********"
until docker system info >/dev/null; do
    sleep 1
done
./opt/ace/serf/handlers/bin/memberupdateswarm
# serf/handlers/member-update.x/swarm
