version: '3.2'

networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_agent_data: {}

services:
  agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
      CAP_HOST_MANAGEMENT: 1
      EDGE_INSECURE_POLL: 1
      EDGE_ID: ${UUID}
      EDGE_KEY: ${EDGE_KEY}
      EDGE: 1
      LOG_LEVEL: DEBUG
    volumes:
      - portainer_agent_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    networks:
      - agent_network
    ports:
      - target: 80
        published: 8001
        protocol: tcp
        mode: host
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
